{
  "@context": "https://security.alpinelinux.org/static/context.jsonld",
  "id": "https://security.alpinelinux.org/branch/3.10-main/vuln-orphaned",
  "items": [
    {
      "@context": "https://security.alpinelinux.org/static/context.jsonld",
      "cpeMatch": [
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "cpeUri": "cpe:2.3:o:xen:xen:*:*:*:*:*:*:arm:*",
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#cpeMatch/10593",
          "maximumVersion": "4.14.1",
          "maximumVersionOp": "<=",
          "minimumVersion": "4.9.0",
          "minimumVersionOp": ">=",
          "package": "https://security.alpinelinux.org/srcpkg/xen",
          "type": "CPEMatch",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2021-26933"
        }
      ],
      "cvss3": {
        "score": 5.5,
        "vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
      },
      "description": "An issue was discovered in Xen 4.9 through 4.14.x. On Arm, a guest is allowed to control whether memory accesses are bypassing the cache. This means that Xen needs to ensure that all writes (such as the ones during scrubbing) have reached the memory before handing over the page to a guest. Unfortunately, the operation to clean the cache is happening before checking if the page was scrubbed. Therefore there is no guarantee when all the writes will reach the memory.",
      "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933",
      "ref": [
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#ref/5807",
          "referenceType": "Patch",
          "rel": "http://xenbits.xen.org/xsa/advisory-364.html",
          "type": "Reference"
        },
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#ref/5808",
          "referenceType": "Mailing List",
          "rel": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/EOAJBVAVR6RSCUCHNXPVSNRPSFM7INMP/",
          "type": "Reference"
        },
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#ref/5809",
          "referenceType": "Mailing List",
          "rel": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4GELN5E6MDR5KQBJF5M5COUUED3YFZTD/",
          "type": "Reference"
        },
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#ref/5810",
          "referenceType": "DEBIAN",
          "rel": "https://www.debian.org/security/2021/dsa-4888",
          "type": "Reference"
        }
      ],
      "state": [
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "fixed": true,
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#state/1324",
          "packageVersion": "https://security.alpinelinux.org/srcpkg/xen/4.14.1-r3",
          "type": "VulnerabilityState",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2021-26933"
        },
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "fixed": true,
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#state/4922",
          "packageVersion": "https://security.alpinelinux.org/srcpkg/xen/4.14.1-r2",
          "type": "VulnerabilityState",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2021-26933"
        },
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "fixed": true,
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#state/8413",
          "packageVersion": "https://security.alpinelinux.org/srcpkg/xen/4.13.2-r5",
          "type": "VulnerabilityState",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2021-26933"
        },
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "fixed": true,
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#state/9925",
          "packageVersion": "https://security.alpinelinux.org/srcpkg/xen/4.13.2-r5",
          "type": "VulnerabilityState",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2021-26933"
        },
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "fixed": true,
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#state/11715",
          "packageVersion": "https://security.alpinelinux.org/srcpkg/xen/4.13.3-r0",
          "type": "VulnerabilityState",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2021-26933"
        },
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "fixed": true,
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#state/11767",
          "packageVersion": "https://security.alpinelinux.org/srcpkg/xen/4.13.3-r0",
          "type": "VulnerabilityState",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2021-26933"
        },
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "fixed": false,
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#state/12118",
          "packageVersion": "https://security.alpinelinux.org/srcpkg/xen/4.12.4-r0",
          "type": "VulnerabilityState",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2021-26933"
        },
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "fixed": true,
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#state/12196",
          "packageVersion": "https://security.alpinelinux.org/srcpkg/xen/4.14.1-r5",
          "type": "VulnerabilityState",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2021-26933"
        },
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "fixed": true,
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#state/13400",
          "packageVersion": "https://security.alpinelinux.org/srcpkg/xen/4.14.1-r3",
          "type": "VulnerabilityState",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2021-26933"
        },
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "fixed": true,
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#state/13434",
          "packageVersion": "https://security.alpinelinux.org/srcpkg/xen/4.13.3-r1",
          "type": "VulnerabilityState",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2021-26933"
        },
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "fixed": true,
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#state/13549",
          "packageVersion": "https://security.alpinelinux.org/srcpkg/xen/4.13.3-r1",
          "type": "VulnerabilityState",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2021-26933"
        },
        {
          "@context": "https://security.alpinelinux.org/static/context.jsonld",
          "fixed": true,
          "id": "https://security.alpinelinux.org/vuln/CVE-2021-26933#state/14978",
          "packageVersion": "https://security.alpinelinux.org/srcpkg/xen/4.14.1-r3",
          "type": "VulnerabilityState",
          "vuln": "https://security.alpinelinux.org/vuln/CVE-2021-26933"
        }
      ],
      "type": "Vulnerability"
    }
  ],
  "type": "Collection"
}